name: Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # Runs every day at 8:00 AM UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Generate Cypress JUnit report
        run: |
          npx cypress run --reporter junit --reporter-options "mochaFile=cypress/results/junit-[hash].xml,toConsole=true"

      - name: List test report files
        run: ls -al cypress/results

      - name: Upload screenshots if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload videos if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload test results (JUnit format)
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/results

    #  - name: Publish test results
    #   uses: dorny/test-reporter@v1
    #   if: always()
    #   with:
    #    name: Cypress Tests
    #    path: cypress/results/junit-*.xml
    #   reporter: go-junit  # Use a more generic JUnit parser
    #   fail-on-error: false
